"""Add name to user

Revision ID: d8725a5c7949
Revises: 0cb11374e0b3
Create Date: 2024-05-04 23:28:14.079365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8725a5c7949'
down_revision = '0cb11374e0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table(
        'emotion_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('emotion', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('emotion_type', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('emotion')
    
    # Adding the 'name' column to 'user' with a default value
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False, server_default='DefaultName'))
    
    # Remove the default value to ensure new rows don't receive it
    op.alter_column('user', 'name', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
    
    op.create_table(
        'emotion',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('emotion_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='emotion_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='emotion_pkey')
    )
    op.drop_table('emotion_data')
    # ### end Alembic commands ###
