"""Add password column to user table

Revision ID: eceaf0e40866
Revises: d8725a5c7949
Create Date: 2024-05-05 17:35:48.507883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceaf0e40866'
down_revision = 'd8725a5c7949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotion_data', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('emotion')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=True))

    # Update existing rows with a default password value
    op.execute("UPDATE \"user\" SET password = 'default_password' WHERE password IS NULL")

    # Make the password column NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password', nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('password')

    with op.batch_alter_table('emotion_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###